config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end

  post 'posts/:id' => 'posts#create', as: 'post_create'
  post 'posts/:post_id/comments' => 'comments#create', as: 'add_comment'

  put 'users/:user_id/:post_id/like' => 'likes#get_like', as: 'like'

  delete 'users/:user_id/:post_id/dislike' => 'likes#dislike', as: 'dislike'


  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  post 'users/:followed_id/follow' => 'relationships#create', as: 'follow'
  delete 'users/:followed_id/unfollow' => 'relationships#destroy', as: 'unfollow'


  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence:true, length: {maximum: 140}
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :caption, length: {maximum: 140}
  has_many_attached :photos

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes

  has_one_attached :avatar
  # validates :avatar, file_size: { less_than_or_equal_to: 100.kilobytes },
  #   file_content_type: { allow: ['image/jpeg', 'image/png'] }


  validates :name, presence: true, length: {maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :pasive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy


  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :pasive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end


  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :avatar, photos: []])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_update_path_for(resource)
   user_path(resource)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post

 def create
   @comment = @post.comments.build(comment_params)
   @comment.user_id = current_user.id

   if @comment.save
     redirect_to post_path(@post.id)
   else
     render :show
   end
 end

 def destroy
   @comment = @post.comments.find(params[:id]).destroy
 end
 private

 def comment_params
   params.require(:comment).permit(:content)
 end
 def set_post
   @post = Post.find(params[:post_id])
 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def get_like
    @post.likes.create(user_id: current_user.id)
    redirect_to request.referrer
  end

  def dislike
    @post.likes.delete(@post.likes.where(user_id: current_user.id))
    redirect_to request.referrer
  end



  private

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    find_post()
    @comment = @post.comments.build
    set_user()
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end

  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_to user_path(current_user.id)
  end

  private

  def post_params
    params.require(:post).permit(:caption, :user_id, photos: [])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def set_user
    find_post()
    @user = User.find(current_user.id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = User.find(params[:followed_id])
    current_user.unfollow(user)
    redirect_to user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :update]
  before_action :require_login
  def index
    @users = User.all
  end

  def show
    @new_post = current_user.posts.build
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end
  
  def followers
     @title = "Followers"
     @user  = User.find(params[:id])
     @users = @user.followers
     render 'show_follow'
   end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: add_comment_path(@comment.post_id), local: true do |f| %>
  <%= f.text_area :content, cols: 60, rows: 5, class: 'mt-3' %>
  <%= f.submit 'Add', class: 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vainglory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/application/navbar' %>

    <div class="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top navbar navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          &#x2630;
        </button>

        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id), class: 'navbar-brand' do %>
            <%= image_tag("logo/logo.png", size: '75x50') %>
          <% end %>
          <%= link_to 'Profile', user_path(current_user.id), class: 'navbar-brand' %>
          <%= link_to 'Feed', posts_path, class: 'navbar-brand' %>
          <%= link_to 'Users', users_path, class: 'navbar-brand' %>
        <% else %>
            <%= image_tag("logo/logo.png", size: '75x50') %>
        <% end %>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <div class="dropdown show">
                <div>
                  <% if current_user.avatar.attached? %>
                    <%= link_to user_path(current_user.id) do %>
                      <%= image_tag current_user.avatar, size: 50, class: "group" %>
                    <% end %>
                  <% end %>
                </div>
                <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
              <div>

              <% else %>
                  <div class="nav-item">
                     <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                  </div>
                  <div class="nav-item">
                     <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                  </div>
              <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/posts/index.html.erb
<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-12">
    <% current_user.followers.each do |followed| %>
      <h1><%= followed.name %></h1>
        <div class="col-3 d-flex flex-column align-items-center">
          <% followed.posts.each do |post| %>
              <%if post.photos.attached? %>
                <% post.photos.each do |photo| %>
                  <%= image_tag photo, size: 250 %>
                <% end %>
              <% end %>
              <%= post.caption %>
              <span>
        </div>
              <%= link_to post_path(post) do %>
                <i class="fa fa-comment"></i>
              <% end %>
              |
              <% if post.likes.exists?(post.likes.where(user_id: current_user.id)) %>
                <%= link_to dislike_path(current_user.id, post.id), method: :delete do %>
                  <i class="fa fa-heart"><%= post.likes.count%></i>
                <% end%>
              <% else %>
                <%= link_to like_path(current_user.id, post.id), method: :put do %>
                  <i class="fa fa-heart-o"><%= post.likes.count%></i>
                <% end%>
              <% end %>
              |
              <% if post.photos.attached? && post.user_id == current_user.id  %>
                <%= link_to post_path(post.id), method: :delete do %>
                    <i class="fa fa-trash"></i>
                <% end %>
              <% end %>
          <% end %>
    <% end %>
</div>
</div>
</div>

app/views/posts/new.html.erb
<h3>Добавить пост</h3>

<%= form_with model: @new_post, url: post_create_path(@new_post.user_id), local: true do |f| %>
  <%= f.file_field :photos, multiple: true %>
  <%= f.label :caption %>
  <%= f.text_area :caption, rows: 3, cols: 20, class: 'mt-3' %>

  <%= f.submit "Add", class: 'btn btn-success' %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% if @post.photos.attached? %>
        <% @post.photos.each do |photo| %>
          <%= image_tag photo, size: 250 %>
        <% end %>
      <% end %>
      <% if @post.likes.exists?(@post.likes.where(user_id: current_user.id)) %>
        <%= link_to dislike_path(current_user.id, @post.id), method: :delete do %>
          <i class="fa fa-heart"><%= @post.likes.count%></i>
        <% end%>
      <% else %>
        <%= link_to like_path(current_user.id, @post.id), method: :put do %>
          <i class="fa fa-heart-o"><%= @post.likes.count%></i>
        <% end%>
      <% end %>
      <%= render template: 'comments/new' %>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <div class="card" style="width: 18rem;">
        <% @post.comments.each do |comment| %>
                <div class="card-body">
                  <h5 class="card-title"><%= User.find(comment.user_id).name %>:</h5>
                  <p class="card-text"> <%= comment.content %></p>
                </div>
        <% end %>
      </div
    </div>
    <%= link_to 'Back', request.referer.present? ? request.referer : default_path %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
<h2><%= user.name %></h2>
<div class="container">
  <div class="row">
    <div class='col d-flex flex-row'>
      <%= link_to user_path(user.id) do %>
          <%= image_tag user.avatar, size: 50, class: "group" %>
      <% end %>
    <div class="col-4">
      <% user ||= current_user %>
        <div>
            <strong>
              <%= link_to following_user_path(user) do %>
                <%= user.following.count %>
                following
              <% end %>
            </strong>
            <strong>
              <%= link_to followers_user_path(user) do %>
                <%= user.followers.count %>
                followers
              <% end %>
            </strong>
        </div>
      <p><%= user.email %></p>
</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="container">
  <div class="row">
    <div class='col-8 d-flex flex-row'>
      <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.avatar, size: 50, class: "group" %>
      <% end %>
    <div class="col-4">
      <% @user ||= current_user %>
        <div>
            <strong>
              <%= link_to following_user_path(@user) do %>
                <%= @user.following.count %>
                following
              <% end %>
            </strong>
            <strong>
              <%= link_to followers_user_path(@user) do %>
                <%= @user.followers.count %>
                followers
              <% end %>
            </strong>
        </div>
      <p><%= @user.email %></p>
      <% if  @user.id != current_user.id %>
        <div>
          <% if current_user.following?(@user) %>
            <%= form_with model: current_user.active_relationships.find_by(followed_id: @user.id),
                          url: unfollow_path(@user.id),
                          method: :delete do |f| %>
                  <%= f.submit "Unfollow", class: "btn btn-danger" %>
            <% end %>
          <% else %>
            <%= form_with model: current_user.active_relationships.build,
                          url: follow_path(@user.id),
                          method: :post do |f| %>
              <%= f.submit "Follow", class: "btn btn-primary" %>
            <% end %>
        <% end %>
        </div>
      <% end %>
    </div>
    </div>
    <div class="col-4">
      <% if user_signed_in? && current_user.id == @user.id %>
        <%= render template: 'posts/new' %>
      <% end %>
    </div>
  </div>
</div>
<div class="container mt-3">
  <div class="row mt-3 justify-content-center">
    <div class="col">
      <% @user.posts.each do |post| %>
        <% if post.photos.attached? %>
          <% if post.photos.size > 1 %>
            <div class="col-3 mt-3">
              <div class="card" >
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <% post.photos.each_with_index do |image, index| %>
                      <li data-target='#carouselExampleControls' data-slide-to="#{index}" class="#{'active' if index == 0}"></li>
                    <% end %>
                  </ol>
                  <div class="carousel-inner">
                      <div class="carousel-item active">
                        <%= link_to image_tag(post.photos.first, size: 250), post_path(post), class: "d-block w-100" %>
                      </div>
                      <% post.photos.drop(1).each do |image| %>
                        <div class="carousel-item">
                          <%= link_to image_tag(image, size: 250), post_path(post), class: "d-block w-100" %>
                        </div>
                      <% end %>
                  </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                </div>
              </div>
          <% else %>
              <% post.photos.each do |image| %>
                <div class="col-3">
                  <div class="card" >
                    <%= link_to image_tag(image, size: 250), post_path(post) %>
                  </div>
                </div>
              <% end %>
          <% end %>
        <% end %>
      <%= post.caption %>
      <span>
        <%= link_to post_path(post) do %>
          <i class="fa fa-comment"></i>
        <% end %>
        |
        <% if post.likes.exists?(post.likes.where(user_id: current_user.id)) %>
          <%= link_to dislike_path(current_user.id, post.id), method: :delete do %>
            <i class="fa fa-heart"><%= post.likes.count%></i>
          <% end%>
        <% else %>
          <%= link_to like_path(current_user.id, post.id), method: :put do %>
            <i class="fa fa-heart-o"><%= post.likes.count%></i>
          <% end%>
        <% end %>
        |
        <% if post.photos.attached? && post.user_id == current_user.id  %>
          <%= link_to post_path(post.id), method: :delete do %>
              <i class="fa fa-trash"></i>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1><%= @user.name %></h1>
    </section>
    <section>
      <% if @users.any? %>
        <div>
          <% @users.each do |user| %>
            <%= link_to user.name, user_path(user.id) %>
          <% end %>
        </div>
      <% end %>
    </section>
    <span><%= link_to "Back", @user %></span>
  </aside>